<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
</head>
<body>
<H1 class="a">ESTO ES UN TUITULO</H1>    
avance
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi quae sit dolorem quia reprehenderit totam soluta at sint? Quibusdam magni assumenda totam obcaecati illum iste nostrum velit maiores repellat officiis.
</body>
</html>